/* Generated By:JavaCC: Do not edit this line. KEGGOrthologyParserConstants.java */
package pt.uminho.sysbio.merlin.gpr.rules.grammar;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface KEGGOrthologyParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 6;
  /** RegularExpression Id. */
  int MINUS = 7;
  /** RegularExpression Id. */
  int ID = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "<ID>",
    "\",\"",
    "\"(\"",
    "\")\"",
  };

}
